version: 2

sources:
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: dim_date_hours
      - name: dim_dates
      - name: dim_labels
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: number_sequence
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: aptos_bronze
    database: aptos
    schema: bronze
    tables:
      - name: lq_blocks_txs
  - name: github_actions
    database: aptos
    schema: github_actions
    tables:
      - name: workflows
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "APTOS_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "APTOS" }}
    tables:
      - name: blocks_tx
      - name: transactions
      - name: transaction_batch
      - name: blocks_tx_v2
      - name: transaction_batch_v2


  