version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'aptos' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: dim_dates
      - name: dim_labels
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'aptos' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: number_sequence
      - name: token_prices_priority_hourly
      - name: token_prices_all_providers_hourly
      - name: asset_metadata_priority
      - name: asset_metadata_all_providers
  - name: aptos_bronze
    database: aptos
    schema: bronze
    tables:
      - name: lq_blocks_txs
  - name: github_actions
    database: aptos
    schema: github_actions
    tables:
      - name: workflows
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "APTOS_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "APTOS" }}
    tables:
      - name: blocks_tx
      - name: transactions
  