version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'aptos' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: address_tags
      - name: dim_dates
  - name: aptos_bronze
    database: aptos
    schema: bronze
    tables:
      - name: lq_blocks_txs
  - name: github_actions
    database: aptos
    schema: github_actions
    tables:
      - name: workflows
